# Exercise 2: Variables :ballot_box_with_check:

#Find a quote from a famous person you admire. Print the quote and the name of its author. 

#Your output should look something like the following, including the quotation marks:

#Albert Einstein once said, “A person who never made a mistake never tried anything new.


print('J. Robert Oppenheimer once said ,“Now, I am become Death, the destroyer of worlds.”')
