# Exercise 5: USB Shopper :ballot_box_with_check:

#A girl heads to a computer shop to buy some USB sticks. She loves USB sticks and wants as many as she can get for £50. They are £6 each.

#Write a programme that calculates how many USB sticks she can buy and how many pounds she will have left.

#You will to use the arithmetic operators to complete this exercise.


total_money = 50
usb_price = 6

print("She can buy", total_money // usb_price, "USB sticks.")

print("She will have £", total_money % usb_price, "left.")
