# Exercise 4:  Large Shirts :ballot_box_with_check:

#Modify the make_shirt() function so that shirts are large by default with a message that reads I love Python. Make a large shirt and a

#medium shirt with the default message, and a shirt of any size with a different message.


def make_shirt(size="L", message="I love Python"):
    """Prints a summary of the shirt's size and the message on it."""
    print(f"The shirt size is {size} and the message printed on it is: '{message}'.")


make_shirt()

make_shirt(size="M")

make_shirt(size="S", message="Code More, Worry Less")
