# Exercise 2: Greetings :ballot_box_with_check:

#Start with the list you used in Exercise 1, but instead of just

#printing each person’s name, print a message to them. The text of each message should be the same, but each message should be 

#personalized with the person’s name.

names = ["ahmed","luigi","zuriel"]

print("hello,"+names[0]+ "! hope you doing well")
print("hello,"+names[1]+ "! do you wanna play football?!")
print("hello,"+names[2]+ "! do you like pizza?")