# Exercise 3: Your Own List :ballot_box_with_check:

#Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. Use your list

#to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”

transportations = ["Tesla car", "dodge challenger car", "Yamaha bike", "yacht"]

print("I would like to own a " + transportations[0] )
print("I would like to own a " + transportations[1] )
print("I would like to own a " + transportations[2] )
print("I would like to own a " + transportations[3] )
