## Exercise 4: Guest List :ballot_box_with_check:

#If you could invite anyone, living or deceased, to dinner, who would you invite? Make a list that includes at least three people you’d

#like to invite to dinner. Then use your list to print a message to each person, invitingthem to dinner.

guests = ["AHMED", "LUIGI", "ZURIEL"]

print("BRO " + guests[0] + ", you are invited to dinner!")
print("BRO " + guests[1] + ", you are invited to dinner!")
print("BRO " + guests[2] + ", you are invited to dinner!")
