## Exercise 1: Person :ballot_box_with_check:

#Use a dictionary to store information about a person you know.Store their first name, last name, age, and the city in which they live. You

#should have keys such as first_name, last_name, age, and city. Print each piece of information stored in your dictionary.

PERSON ={
    'first_name': 'mohammed',
    'last_name': 'bahri',
    'age': '18',
    'city': 'abu dhabi'}

print('first name:', PERSON['first_name'])
print('last name:', PERSON['last_name'])
print('age:', PERSON['age'])
print('city:',PERSON['city'])