
## Exercise 1: Print Strings :ballot_box_with_check:

#Write a Python program to print the following string in a specific format.

#Twinkle, twinkle, little star,
##		Up above the world so high,   		
#		Like a diamond in the sky. 
#Twinkle, twinkle, little star, 
#	How I wonder what you are

#\t - Adds a tab (indentation) before the line.


print('Twinkle, twinkle, little star,')
print('\tUp above the world so high,')  #We use \t before lines that need indentation.
print('\tLike a diamond in the sky.') #We use \t before lines that need indentation.
print('Twinkle, twinkle, little star,')
print('\tHow I wonder what you are')  #We use \t before lines that need indentation.