## Exercise 5: Compute area of Circle :ballot_box_with_check:

#Write a Python program which accepts the radius of a circle from the user and compute the area.

# Step 1: Ask the user to type in the radius


radius = float(input("Enter the radius of the circle: "))

area = 3.14 * radius * radius  #3.14 is a number that’s close to 𝜋 (pi), which we use for circles.


print("The area of the circle is:", area)
